---
- name:  check for all available updates from satellite
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: check for available updates
      yum:
        list: updates
        update_cache: true
      register: yumoutput

    - name: set the result count fact
      set_fact:
        result_count: "{{ yumoutput.results | map(attribute='name') | list| length }}"
    - name: see the count of available updates per host only when updates available
      debug:
        msg: "There are {{ result_count }} available updates to install on {{ inventory_hostname }}"
      when: result_count.value > 0