---
- name:  check for all available updates from satellite
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: check for available updates
      yum:
        list: updates
        update_cache: true
      register: yumoutput
    - name: see the list of available updates per hosts
      debug:
        msg: "{{ yumoutput.results | map(attribute='name') | list| length }}"