---
- name: promote a satellite content view
  hosts: "{{ HOSTS | default('satellite') }}"
  vars_files: satellite_connection_credentials.yml
  collections:
    - redhat.satellite
  tasks:
    - name: promote a content view
      content_view_version:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        content_view: "{{ satellite_cv_name }}"
        organization: "{{ satellite_org_name }}"
        current_lifecycle_environment: "{{ current_lc_env }}"
        lifecycle_environments:
          - "{{ satellite_lc_env }}"
        description: Promoted on {{ lookup('pipe', 'date') }}