---
- name: reboot a system
  hosts: all
  become: true
  tasks:
    - name: reboot a system
      reboot:
        reboot_timeout: 1200
        msg: "Reboot intiated by Ansible for regular patching"
        pre_reboot_delay: 60
        post_reboot_delay: 60
