---
- name: subscribe a RHEL system to Satellite
  hosts: all
  become: true
  tasks:
    - name: subscribe to satellite
      community.general.redhat_subscription:
        activationkey: "{{ satellite_management_akey_id }}"
        org_id: "{{satellite_management_org_id }}"
        state: present
        auto_attach: true