---
- name: synchronize a capsule via hammer and shell module
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: synchronize a capsule using hammer
      ansible.builtin.shell:
        cmd: hammer --quiet capsule content synchronize --name {{ satellite_management_capsule_name }}